name: Gitflow Release
env:
  STAGING_BRANCH: dev
  PRODUCTION_BRANCH: master
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FD_DEPLOYER_TOKEN: ${{ secrets.freshchat_deployer_pat }}
  RELEASETAG_REGEX: (\d+\.){3}\d+
on:
  pull_request:
    types: 
      - closed
    branches: 
      - master
jobs:
  create_release:
    name: Freshchat GitFlow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          repository: freshdesk/freshchat-gitapps
          ref: master
          fetch-depth: 1
          token: ${{ env.FD_DEPLOYER_TOKEN }}
          path: freshchat-gitapps
       
      - name: Install Release Dependencies
        if: github.base_ref == env.PRODUCTION_BRANCH && success()
        run: npm install --prefix ./freshchat-gitapps/actions/gitflow_release/
      - name: Release
        id: gitflow_release
        if: github.base_ref == env.PRODUCTION_BRANCH && success()
        uses: ./freshchat-gitapps/actions/gitflow_release/
        with:
          production_branch: ${{ env.PRODUCTION_BRANCH }} 
          staging_branch: ${{ env.STAGING_BRANCH }}
          releasetag_regex: ${{ env.RELEASETAG_REGEX }}
